collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1197637
color:
  saturation: 1
  brandStrength: 0.3055854
  lightness: 1
  brandColors:
    - '#000000'
    - '#FFFFFD'
    - '#D6B997'
    - '#76796E'
    - '#353E45'
  rhythmicContrast: 1
layout_spectrum: 1
name: AnitaSam
