layout_spectrum: 1
color:
  saturation: 1
  lightness: 1
  brandStrength: 1
  brandColors:
    - '#000000'
    - '#FFFFFD'
    - '#D6B997'
    - '#76796E'
    - '#353E45'
  rhythmicContrast: 1
typography_spectrum: 0.2669173
name: AnitaSam
